[package]
name = "bevy_vello_graphics"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = { version = "0.14.2", default-features = false }
bevy_vello = "0.6.1"

[lints.clippy]
redundant_type_annotations = "warn"
bool_comparison = "allow"
